---
abstract: 'Perl interface for the certificate handling parts of the NSS api.'
author:
  - 'Bernhard Amann, <bernhard@icsi.berkeley.edu>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 2.21
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mozilla
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-NSS-X509
no_index:
  directory:
    - inc
    - t
requires:
  Exporter: 5.65
  MIME::Base64: 3.13
  XSLoader: 0.02
  autodie: 2.1
  perl: 5.10.1
resources:
  bugtracker: https://github.com/amannb/perl-nss/issues
  homepage: https://github.com/amannb/perl-nss
  license: http://opensource.org/licenses/mozilla1.1.php
version: 0.01_2
